### ISSUE TITLE
Add colonial Formables

### ISSUE THREAD

**Issue by Kajmak1** [Kajmak1/Greenskin-Gaming-mod#41]
- Only formable when the entire colonial region is owned.
- Estates enabled
- Better Gov reforms
- Custom National ideas
- Names depending on the overlord

**Comment by Mitch648** [comment]
Only formable when the entire colonial region is owned. -Done 

Still to do: custom national Ideas  Most tags only have generic ideas. Tags/Regions that need ideas are Louisiana, Columbia, La Plata, Peru, Venezuela, California. I didn't include the nations that weren't included in C28. Some nation ideas need a buff, in my opinion, Canada, Brazil, West Indies. I would also remove ideas that have core creation cost, a colonist and colonial growth, as they won't use any of this by the time they form. Nations having one of these include Canada, Brazil, Australia, New Zealand,  Vermont, and the West Indies.

Enable Estates

Better Government Reforms.
